version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mxsocialflow
    container_name: mxsocialflow-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - mxsocialflow

  webserver:
    image: nginx:alpine
    container_name: mxsocialflow-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - mxsocialflow

  db:
    image: mysql:5.7
    container_name: mxsocialflow-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - mxsocialflow

networks:
  mxsocialflow:
    driver: bridge

volumes:
  dbdata:
    driver: local